var eventStore,workshopStore;
gotDataQuery2019=function(a){var d="<div class='panel-group' id='accordion'>";if(0==a.length)d+="<span class='text-normal'>Sorry, no events for selected criteria.</span></div>";else{d=1<a.length?d+("<div class='title-second' id='box-text'>"+a.length+" Events</div>"):d+"<div class='title-second' id='box-text'>One Event</div>";for(var b=0;b<a.length;b++){d+="<div class='panel panel-default'><div class='panel-heading'><h4 class='panel-title'><a data-toggle='collapse' data-parent='#accordion' href='#collapse"+b+
"'><p class='title-third'>";d+=a[b].Date+"<br><span style='color: #011689;'>"+String(a[b].Title).replace(/""/g,'"')+"</span></p></a></h4></div>";d=0==b?d+("<div id='collapse"+b+"' class='panel-collapse collapse in'><div class='panel-body'>"):d+("<div id='collapse"+b+"' class='panel-collapse collapse'><div class='panel-body'>");d+="<div>";""!=a[b].Program&&(d+=String(a[b].Program).replace(/""/g,'"')+"<br>");d+=String(a[b].Times).replace(/""/g,'"')+" | "+a[b].Cost+"</div>";var c="",e="";""!=a[b].Images&&
(c+="<img src='/wp-content/themes/Divi-child/thumbnails/"+a[b].Images+"T.jpg' style='width:150px;height:200px;margin:5px;border:solid 1px #999;padding:2px; float:right;' title='"+a[b].Title+"'  />",""!=a[b].Credit&&(e="<span class='text-small' style='float:right; clear: both;'>Image Credit: "+a[b].Credit+"</span>"));d+="<div><p><br>"+c+String(a[b].Description).replace(/""/g,'"')+"<br>"+e+"</p></div>";d+="<div style='clear: both;'><br><b>"+a[b].Location+"</b><br>&nbsp;&nbsp;"+a[b].Address;c=(new String(a[b].Address)).split(/,|\(/)[0];
-1!=c.search(/opera/i)?c="705 Court C":-1!=c.search(/2926 S. Steele St./i)?c="2926 S. Steele St.":-1!=c.search(/1901 Commerce St./i)&&(c="1901 Commerce St.");c=c.replace("&","and");d+=' - <a href="http://maps.google.com/maps?f=q&hl=en&geocode=&q='+c+",Tacoma,WA\" target='_blank' title='Open Google Map with location.'>Map It</a>";""!=a[b].Phone&&(d+="<br>&nbsp;&nbsp;Contact: "+a[b].Phone);""!=a[b].Web&&(d+="<br><span style='word-wrap:break-word; width:248px;'>&nbsp;&nbsp;Website: <a href='http://"+
a[b].Web+"' target=_blank>"+a[b].Web+"</a></span>");d+="<br>&nbsp;</div>";c=a[b].Category+"";"|"==c.substr(0,1)&&(c=c.substring(1));e=c.length;"|"==c.substr(e-1,1)&&(c=c.substring(0,e-1));d+="<div><i>"+c+"</i></div>";d+="<div>";"Yes"==a[b].Wheelchair&&(d+="<img src='/wp-content/themes/Divi-child/images/Logo/Wheelchair.jpg' title='wheelchair accessible venue' style='width:20px;height:20px; float: right;padding:4px;' align='top'>");"Yes"==a[b].Funded&&(d+="<img src='/wp-content/themes/Divi-child/images/Logo/TACfunded.jpg' title='funded by Tacoma Arts Commission in 2019' style='width:20px;height:20px; float: right;padding:4px;' align='top'>");
d+="</div>";0!=b&&(d+="<div class='box-line'></div>",d+="<div style='clear:both;'><a href='#top'>Back to top of page</a></div>");d+="</div></div></div>"}d+="</div></div>"}document.getElementById("Events").innerHTML=d};
gotDataQueryStudioTours=function(a,d){var b="<div class='panel-group' id='accordion'>";if(0==a.length)b+="<span class='text-normal'>Sorry...</span></div></div>";else{for(var c=0;c<a.length;c++){b+="<div class='panel panel-default'><div class='panel-heading'><h4 class='panel-title'><a data-toggle='collapse' data-parent='#accordion' href='#collapse"+c+"'><p class='title-third'>";b+="<span style='color: #011689;'>"+a[c].FirstName+" "+a[c].LastName+"</span> Studio #"+a[c].StudioNumber+"<br><span class='text-normal'>"+
a[c].Media+"</span></p></a></h4></div>";b=0==c?b+("<div id='collapse"+c+"' class='panel-collapse collapse in'><div class='panel-body'>"):b+("<div id='collapse"+c+"' class='panel-collapse collapse'><div class='panel-body'>");b+="<div>";b+='<img style="float:left;width:75px;height:100px;margin:0px 10px 5px 5px;border:solid 1px #999;padding:2px" src="/wp-content/themes/Divi-child/images/studios/'+a[c].PhotoFileName+'T.jpg" title="'+a[c].FirstName+" "+a[c].LastName+'"/>';b+="<b>"+a[c].FirstName+" "+a[c].LastName;
""!=a[c].BusinessName&&(b+=" | "+a[c].BusinessName);b+="</b><br>";b+="<i>"+a[c].Media+"</i><br>";b+="</div><div style='clear:both;'>";b+=a[c].ArtistStatement+"<br>";b+="<span class='text-info'><br><b>Open "+a[c].DayPreference+"</b><br>&nbsp;"+a[c].StudioAddress+"<br>";""!=a[c].AccessDirection&&(b+="<i>"+a[c].AccessDirection+"</i><br>");""!=a[c].Phone&&(b+=a[c].Phone+"<br>");""!=a[c].Email&&(b+="<a href='mailto:"+a[c].Email+"?subject=Art At Work Studio Tour'>"+a[c].Email+"</a><br>&nbsp;");""!=a[c].Website&&
(b+="<a href='http://"+a[c].Website+"' target=_blank>"+a[c].Website+"</a><br>&nbsp;");b+="</span>";""!=a[c].Demo&&(b+="<p><b>DEMO: </b>"+a[c].Demo+"</p>");var e=3;"Saturday"==a[c].DayPreference?e=1:"Sunday"==a[c].DayPreference&&(e=2);var f=(new String(a[c].StudioAddress)).split(/,|\(/)[0];-1!=f.search(/opera/i)?f="705 Court C":-1!=f.search(/2926 S. Steele St./i)?f="2926 S. Steele St.":-1!=f.search(/1901 Commerce St./i)&&(f="1901 Commerce St.");f=f.replace("&","and");b+="<p class='text-normal'> <span style='text-align: left;'><a href=\"https://wspdsmap.cityoftacoma.org/website/HistoricMap/scripts/calendar/Calendar.asp?Day="+
e+"&Studio="+a[c].StudioNumber+"&Address="+a[c].StudioAddress+"&Name="+a[c].FirstName+" "+a[c].LastName+"\" target='_blank' title='Open file to add appointment to your calendar.'>Add to Calendar</a><br>";b+='<a href="http://maps.google.com/maps?f=q&hl=en&geocode=&q='+f+",Tacoma,WA\" target='_blank' title='Open Google Map of Studio location.'>Map It</a></span></p>";"Yes"==a[c].Wheelchair&&(b+='<img src="/wp-content/themes/Divi-child/images/Logo/Wheelchair.jpg" title="wheelchair accessible studio" style="width:20px;height:20px;margin:2px 5px 5px 0px;border:solid 1px #999;padding:2px;">');
"Yes"==a[c].FundedbyTAC&&(b+='<img src="/wp-content/themes/Divi-child/images/Logo/TACfunded.jpg" title="artist funded by Tacoma Arts Commission in 2019" style="width:20px;height:20px;margin:2px 5px 5px 0px;border:solid 1px #999;padding:2px;">');"Yes"==a[c].GTCF&&(b+='<img src="/wp-content/themes/Divi-child/images/Logo/GTCF.jpg" title="artist nominated for Greater Tacoma Community Foundation\'s Foundation of Art Award" style="width:20px;height:20px;margin:2px 5px 5px 0px;border:solid 1px #999;padding:2px;">');
"Yes"==a[c].PassportItem&&(b+='<img src="/wp-content/themes/Divi-child/images/Logo/Passport.jpg" title="artwork by these artists are included in Studio Tour Passport prize packages" style="width:20px;height:20px;margin:2px 5px 5px 0px;border:solid 1px #999;padding:2px;">');b+="</div>";b+="</div></div></div>"}b+="</div>"}d("#StudioTours").html(b)};
gotDataQueryExhibits=function(a,d){var b="<div class='panel-group' id='accordion'>";if(0==a.length)b+="<span class='text-normal'>Sorry, no exhibits for selected criteria.</span></div>";else{b=1<a.length?b+("<div class='title-second' id='box-text'>"+a.length+" Exhibits</div>"):b+"<div class='title-second' id='box-text'>One Exhibit</div>";for(var c=0;c<a.length;c++){b+="<div class='panel panel-default'><div class='panel-heading'><h4 class='panel-title'><a data-toggle='collapse' data-parent='#accordion' href='#collapse"+
c+"'><p class='title-third'>";b+=a[c].Date+"<br><span style='color: #011689;'>"+a[c].Title+"</span></p></a></h4></div>";b=0==c?b+("<div id='collapse"+c+"' class='panel-collapse collapse in'><div class='panel-body'>"):b+("<div id='collapse"+c+"' class='panel-collapse collapse'><div class='panel-body'>");""!=a[c].Program&&(b+=String(a[c].Program).replace(/""/g,'"')+"<br>");b+="<div>"+String(a[c].Time).replace(/""/g,'"')+" | "+a[c].Cost+"</div>";var e="",f="";""!=a[c].Images&&(e+="<img src='/wp-content/themes/Divi-child/thumbnails/"+
a[c].Images+"T.jpg' style='width:150px;height:200px;margin:5px;border:solid 1px #999;padding:2px; float:right;' title='"+a[c].Title+"'  />",""!=a[c].Credit&&(f="<span class='text-small' style='float:right; clear: both;'>Image Credit: "+a[c].Credit+"</span>"));b+="<div><p><br>"+e+String(a[c].Description).replace(/""/g,'"')+"<br>"+f+"</p></div>";b+="<div style='clear: both;'><br><b>"+a[c].Location+"</b><br>&nbsp;&nbsp;"+a[c].Address;e=(new String(a[c].Address)).split(/,|\(/)[0];-1!=e.search(/opera/i)?
e="705 Court C":-1!=e.search(/2926 S. Steele St./i)?e="2926 S. Steele St.":-1!=e.search(/1901 Commerce St./i)&&(e="1901 Commerce St.");e=e.replace("&","and");b+=' - <a href="http://maps.google.com/maps?f=q&hl=en&geocode=&q='+e+",Tacoma,WA\" target='_blank' title='Open Google Map with location.'>Map It</a>";""!=a[c].Phone&&(b+="<br>&nbsp;&nbsp;Contact: "+a[c].Phone);""!=a[c].Web&&(b+="<br><span style='word-wrap:break-word; width:248px;'>&nbsp;&nbsp;Website: <a href='http://"+a[c].Web+"' target=_blank>"+
a[c].Web+"</a></span>");b+="<br>&nbsp;</div>";e=a[c].Category+"";"|"==e.substr(0,1)&&(e=e.substring(1));f=e.length;"|"==e.substr(f-1,1)&&(e=e.substring(0,f-1));b+="<div><i>"+e+"</i></div>";b+="<div>";"Yes"==a[c].Wheelchair&&(b+="<img src='/wp-content/themes/Divi-child/images/Logo/Wheelchair.jpg' title='wheelchair accessible venue' style='width:20px;height:20px; float: right;padding:4px;' align='top'>");"Yes"==a[c].Funded&&(b+="<img src='/wp-content/themes/Divi-child/images/Logo/TACfunded.jpg' title='funded by Tacoma Arts Commission in 2019' style='width:20px;height:20px; float: right;padding:4px;' align='top'>");
b+="</div>";0!=c&&(b+="<div class='box-line'></div>",b+="<div style='clear:both;'><a href='#top'>Back to top of page</a></div>");b+="</div></div></div>"}b+="</div></div>"}document.getElementById("Exhibits").innerHTML=b};
gotDataQueryClasses=function(a){var d="<div class='panel-group' id='accordion'>";if(0==a.length)d+="<span class='text-normal'>Sorry, no classes for selected criteria.</span></div>";else{d+="<div class='title-second' id='box-text'>"+a.length+" Classes</div>";for(var b=0;b<a.length;b++){d+="<div class='panel panel-default'><div class='panel-heading'><h4 class='panel-title'><a data-toggle='collapse' data-parent='#accordion' href='#collapse"+b+"'><p class='title-third'>";d+=a[b].Date+"<br><span style='color: #011689;'>"+
a[b].Title+"</span></p></a></h4></div>";d=0==b?d+("<div id='collapse"+b+"' class='panel-collapse collapse in'><div class='panel-body'>"):d+("<div id='collapse"+b+"' class='panel-collapse collapse'><div class='panel-body'>");""!=a[b].Program&&(d+=String(a[b].Program).replace(/""/g,'"')+"<br>");d+="<div>"+String(a[b].Time).replace(/""/g,'"')+" | "+a[b].Cost+"</div>";var c="",e="";""!=a[b].Images&&(c+="<img src='/wp-content/themes/Divi-child/thumbnails/"+a[b].Images+"T.jpg' style='width:150px;height:200px;margin:5px;border:solid 1px #999;padding:2px; float:right;' title='"+
a[b].Title+"'  />",""!=a[b].Credit&&(e="<span class='text-small' style='float:right; clear: both;'>Image Credit: "+a[b].Credit+"</span>"));d+="<div><p><br>"+c+String(a[b].Description).replace(/""/g,'"')+"<br>"+e+"</p></div>";d+="<div style='clear: both;'><br><b>"+a[b].Location+"</b><br>&nbsp;&nbsp;"+a[b].Address;c=(new String(a[b].Address)).split(/,|\(/)[0];-1!=c.search(/opera/i)?c="705 Court C":-1!=c.search(/2926 S. Steele St./i)?c="2926 S. Steele St.":-1!=c.search(/1901 Commerce St./i)&&(c="1901 Commerce St.");
c=c.replace("&","and");d+=' - <a href="http://maps.google.com/maps?f=q&hl=en&geocode=&q='+c+",Tacoma,WA\" target='_blank' title='Open Google Map with location.'>Map It</a>";""!=a[b].Phone&&(d+="<br>&nbsp;&nbsp;Contact: "+a[b].Phone);""!=a[b].Web&&(d+="<br><span style='word-wrap:break-word; width:248px;'>&nbsp;&nbsp;Website: <a href='http://"+a[b].Web+"' target=_blank>"+a[b].Web+"</a></span>");d+="<br>&nbsp;</div>";c=a[b].Category+"";"|"==c.substr(0,1)&&(c=c.substring(1));e=c.length;"|"==c.substr(e-
1,1)&&(c=c.substring(0,e-1));d+="<div><i>"+c+"</i></div>";d+="<div>";"Yes"==a[b].Wheelchair&&(d+="<img src='/wp-content/themes/Divi-child/images/Logo/Wheelchair.jpg' title='wheelchair accessible venue' style='width:20px;height:20px; float: right;padding:4px;' align='top'>");"Yes"==a[b].Funded&&(d+="<img src='/wp-content/themes/Divi-child/images/Logo/TACfunded.jpg' title='funded by Tacoma Arts Commission in 2019' style='width:20px;height:20px; float: right;padding:4px;' align='top'>");d+="</div>";
0!=b&&(d+="<div class='box-line'></div>",d+="<div style='clear:both;'><a href='#top'>Back to top of page</a></div>");d+="</div></div></div>"}d+="</div></div>"}document.getElementById("Activities_Classes").innerHTML=d};
_filterWatch=function(a){if(null!=document.getElementById("date1")){a("#date1").datepicker("option",{maxDate:a("#date2").datepicker().val()});a("#date2").datepicker("option",{minDate:a("#date1").datepicker().val()});a("#theActTitle").html(a("#categorySelect").val()+" | "+a("#date1").datepicker({dateFormat:"mm-dd-yyyy"}).val()+" - "+a("#date2").datepicker({dateFormat:"mm-dd-yyyy"}).val());var d=new Date(a("#date1").val()),b=new Date(d.getFullYear(),d.getMonth(),d.getDate()-1);d=b.getDate();var c=b.getMonth()+
1;b=b.getFullYear();10>d&&(d="0"+d);10>c&&(c="0"+c);var e=c+"/"+d+"/"+b;eventStore_filtered=eventStore.filter(function(b){return"All Activities"==a("#categorySelect").val()?b.Date>=e&&b.Date<=a("#date2").datepicker({dateFormat:"mm-dd-yyyy"}).val():0<=b.Category.indexOf(a("#categorySelect").val())&&b.Date>=e&&b.Date<=a("#date2").datepicker({dateFormat:"mm-dd-yyyy"}).val()});gotDataQuery2019(eventStore_filtered)}};
_filterWatchWorkshops=function(a){a("#theActTitle").html(a("#categorySelectWorkshops").val());workshopStore_filtered=workshopStore.filter(function(d){return"All"==a("#categorySelectWorkshops").val()?workshopStore:0<=d.Category.indexOf(a("#categorySelectWorkshops").val())});gotDataQueryClasses(workshopStore_filtered)};
jQuery(document).ready(function(a){var d=new Date,b=d.getDate(),c=d.getMonth()+1;d=d.getFullYear();10>b&&(b="0"+b);10>c&&(c="0"+c);b=c+"/"+b+"/"+d;if("09/07/2019">b||"11/15/2019"<b)b="09/07/2019";a("#date1").datepicker({minDate:"09/07/2019",maxDate:"11/15/2019",onSelect:function(b){_filterWatch(a)}});a("#date1").datepicker().datepicker("setDate",b);a("#date2").datepicker({minDate:"09/07/2019",maxDate:"11/15/2019",onSelect:function(b){_filterWatch(a)}});a("#date2").datepicker().datepicker("setDate",
"11/15/2019");a("#startDateWorkshops").datepicker({minDate:"09/07/2019",maxDate:"11/15/2019",onSelect:function(b){_filterWatchWorkshops(a)}});a("#startDateWorkshops").datepicker().datepicker("setDate",b);a("#endDateWorkshops").datepicker({minDate:"09/07/2019",maxDate:"11/15/2019",onSelect:function(b){_filterWatchWorkshops(a)}});a("#endDateWorkshops").datepicker().datepicker("setDate","11/15/2019");a("#categorySelect").selectmenu({});a("#categorySelect").append(a("<option>",{value:"All Activities",
text:"All Activities"}));a("#categorySelect").append(a("<option>",{value:"For Kids",text:"Children\u2019s Program"}));a("#categorySelect").append(a("<option>",{value:"Comedy",text:"Comedy"}));a("#categorySelect").append(a("<option>",{value:"Community Event",text:"Community Event"}));a("#categorySelect").append(a("<option>",{value:"Culinary Arts",text:"Culinary"}));a("#categorySelect").append(a("<option>",{value:"Cultural Event",text:"Cultural"}));a("#categorySelect").append(a("<option>",{value:"Dance",
text:"Dance"}));a("#categorySelect").append(a("<option>",{value:"Digital",text:"Digital"}));a("#categorySelect").append(a("<option>",{value:"Educational",text:"Educational"}));a("#categorySelect").append(a("<option>",{value:"Featured Event",text:"Featured Event"}));a("#categorySelect").append(a("<option>",{value:"Film",text:"Film"}));a("#categorySelect").append(a("<option>",{value:"Fundraiser",text:"Fundraiser"}));a("#categorySelect").append(a("<option>",{value:"History",text:"History"}));a("#categorySelect").append(a("<option>",
{value:"Interdisciplinary",text:"Interdisciplinary"}));a("#categorySelect").append(a("<option>",{value:"Lecture",text:"Lecture"}));a("#categorySelect").append(a("<option>",{value:"Literary",text:"Literary"}));a("#categorySelect").append(a("<option>",{value:"Metal",text:"Metal"}));a("#categorySelect").append(a("<option>",{value:"Music",text:"Music"}));a("#categorySelect").append(a("<option>",{value:"Nightlife",text:"Nightlife"}));a("#categorySelect").append(a("<option>",{value:"Opera",text:"Opera"}));
a("#categorySelect").append(a("<option>",{value:"Other",text:"Other"}));a("#categorySelect").append(a("<option>",{value:"Theater",text:"Theater"}));a("#categorySelect").append(a("<option>",{value:"Visual Art",text:"Visual Art"}));a("#categorySelect").append(a("<option>",{value:"Wearable Art",text:"Wearable Art"}));a("#categorySelect").selectmenu("refresh");a("#categorySelect").on("selectmenuselect",function(){_filterWatch(a)});a("#categorySelectWorkshops").selectmenu({});a("#categorySelectWorkshops").append(a("<option>",
{value:"All",text:"All"}));a("#categorySelectWorkshops").append(a("<option>",{value:"For Kids",text:"Children\u2019s Program"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Comedy",text:"Comedy"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Community Event",text:"Community Event"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Culinary Arts",text:"Culinary Arts"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Cultural Event",text:"Cultural Event"}));
a("#categorySelectWorkshops").append(a("<option>",{value:"Dance",text:"Dance"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Digital",text:"Digital"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Educational",text:"Educational"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Film",text:"Film"}));a("#categorySelectWorkshops").append(a("<option>",{value:"History",text:"History"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Interdisciplinary",text:"Interdisciplinary"}));
a("#categorySelectWorkshops").append(a("<option>",{value:"Lecture",text:"Lecture"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Literary",text:"Literary"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Metal",text:"Metal"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Music",text:"Music"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Nightlife",text:"Nightlife"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Opera",text:"Opera"}));
a("#categorySelectWorkshops").append(a("<option>",{value:"Other",text:"Other"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Theater",text:"Theater"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Visual Art",text:"Visual Art"}));a("#categorySelectWorkshops").append(a("<option>",{value:"Wearable Art",text:"Wearable Art"}));a("#categorySelectWorkshops").selectmenu("refresh");a("#categorySelectWorkshops").on("selectmenuselect",function(){_filterWatchWorkshops(a)});document.getElementById("Events")&&
d3.json("/wp-content/themes/Divi-child/text_files/Events2019.txt?v=20190903",function(b){eventStore=b;_filterWatch(a)});document.getElementById("Exhibits")&&d3.json("/wp-content/themes/Divi-child/text_files/Exhibits2019.txt?v=20190903",function(b){gotDataQueryExhibits(b,a)});document.getElementById("Activities_Classes")&&d3.json("/wp-content/themes/Divi-child/text_files/OctWorkshops2019.txt?v=20191001",function(b){workshopStore=b;_filterWatchWorkshops(a)});document.getElementById("StudioTours")&&
a.getJSON("/wp-content/themes/Divi-child/text_files/StudioTours2019.txt?v=20190903",function(b){gotDataQueryStudioTours(b,a)})});